# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.7
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_nrfl', [dirname(__file__)])
        except ImportError:
            import _nrfl
            return _nrfl
        if fp is not None:
            try:
                _mod = imp.load_module('_nrfl', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _nrfl = swig_import_helper()
    del swig_import_helper
else:
    import _nrfl
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0



def setup():
  return _nrfl.setup()
setup = _nrfl.setup

def NextSenderId():
  return _nrfl.NextSenderId()
NextSenderId = _nrfl.NextSenderId
class ArPiMessage(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ArPiMessage, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ArPiMessage, name)
    __repr__ = _swig_repr
    __swig_setmethods__["sender_id"] = _nrfl.ArPiMessage_sender_id_set
    __swig_getmethods__["sender_id"] = _nrfl.ArPiMessage_sender_id_get
    if _newclass:sender_id = _swig_property(_nrfl.ArPiMessage_sender_id_get, _nrfl.ArPiMessage_sender_id_set)
    __swig_setmethods__["data"] = _nrfl.ArPiMessage_data_set
    __swig_getmethods__["data"] = _nrfl.ArPiMessage_data_get
    if _newclass:data = _swig_property(_nrfl.ArPiMessage_data_get, _nrfl.ArPiMessage_data_set)
    __swig_setmethods__["parity"] = _nrfl.ArPiMessage_parity_set
    __swig_getmethods__["parity"] = _nrfl.ArPiMessage_parity_get
    if _newclass:parity = _swig_property(_nrfl.ArPiMessage_parity_get, _nrfl.ArPiMessage_parity_set)
    def __init__(self): 
        this = _nrfl.new_ArPiMessage()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _nrfl.delete_ArPiMessage
    __del__ = lambda self : None;
ArPiMessage_swigregister = _nrfl.ArPiMessage_swigregister
ArPiMessage_swigregister(ArPiMessage)


def new_ArPiMessageP():
  return _nrfl.new_ArPiMessageP()
new_ArPiMessageP = _nrfl.new_ArPiMessageP

def copy_ArPiMessageP(*args):
  return _nrfl.copy_ArPiMessageP(*args)
copy_ArPiMessageP = _nrfl.copy_ArPiMessageP

def delete_ArPiMessageP(*args):
  return _nrfl.delete_ArPiMessageP(*args)
delete_ArPiMessageP = _nrfl.delete_ArPiMessageP

def ArPiMessageP_assign(*args):
  return _nrfl.ArPiMessageP_assign(*args)
ArPiMessageP_assign = _nrfl.ArPiMessageP_assign

def ArPiMessageP_value(*args):
  return _nrfl.ArPiMessageP_value(*args)
ArPiMessageP_value = _nrfl.ArPiMessageP_value
# This file is compatible with both classic and new-style classes.


